# Generated by Django 3.1.2 on 2020-11-01 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_name', models.CharField(max_length=50)),
                ('comment', models.TextField()),
                ('public_key', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=50)),
                ('batch', models.CharField(max_length=50)),
                ('rack', models.CharField(max_length=50)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='samples', to='app.key')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('name_encrypted', models.CharField(max_length=200)),
                ('address_encrypted', models.CharField(max_length=200)),
                ('contact_encrypted', models.CharField(max_length=200)),
                ('password_hash', models.CharField(max_length=200)),
                ('public_key_fingerprint', models.CharField(max_length=200)),
                ('session_key_encrypted', models.CharField(max_length=1000)),
                ('aes_instance_iv', models.CharField(max_length=200)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='app.sample')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('comment', models.TextField()),
                ('updated_on', models.DateTimeField()),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='app.sample')),
            ],
        ),
    ]
