# Generated by Django 3.1.6 on 2021-03-30 13:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_consent'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('comment', models.TextField(blank=True, null=True)),
                ('relevant', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
    ]
