# Generated by Django 3.1.8 on 2021-04-16 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_auto_20210415_0911"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SampleRecipient",
            new_name="BagRecipient",
        ),
    ]
