# Generated by Django 3.1.8 on 2021-04-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_auto_20210416_0950"),
    ]

    operations = [
        migrations.AddField(
            model_name="bagrecipient",
            name="billing_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bagrecipient",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
