# Generated by Django 3.1.8 on 2021-04-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_auto_20210416_0951"),
    ]

    operations = [
        migrations.AddField(
            model_name="bag",
            name="handed_out_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
