# Generated by Django 3.1.8 on 2021-05-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_bag_handed_out_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bagrecipient",
            name="recipient_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("offers tests regularly to their staff", "Institution"),
                    (
                        "one-off or recurring event where students are tested",
                        "Teaching Event",
                    ),
                    ("invoice goes to the organizer of the event", "One-Off Event"),
                    ("bag goes to internal", "Internal"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
