# Generated by Django 3.1.8 on 2022-01-17 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210503_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
