# Generated by Django 4.0.1 on 2022-02-17 01:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_pushabonnement_alter_registration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushabonnement',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
