# Generated by Django 4.0.1 on 2022-02-17 14:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_pushabonnement_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pushabonnement',
            name='id',
        ),
        migrations.AddField(
            model_name='pushabonnement',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
