# Generated by Django 4.0.1 on 2022-02-17 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_pushabonnement_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pushabonnement',
            old_name='id',
            new_name='uuid',
        ),
    ]
