# Generated by Django 4.0.1 on 2022-02-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_pushabonnement_id_pushabonnement_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pushabonnement',
            name='uuid',
        ),
        migrations.AddField(
            model_name='pushabonnement',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
