# Generated by Django 4.0.1 on 2022-02-17 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_pushabonnement_uuid_pushabonnement_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PushAbonnement',
        ),
    ]
