# Generated by Django 4.0.1 on 2022-05-16 00:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_news_front_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushabonnement',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
