# Generated by Django 4.0.1 on 2022-05-16 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_news_front_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
