# Generated by Django 4.0.1 on 2022-05-16 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_pushabonnement_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushabonnement',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
