# Generated by Django 4.0.1 on 2022-06-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_registration_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='access_page',
            field=models.BooleanField(default=False, verbose_name='Visible on Access-Checking page (page to enter access code)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='front_page',
            field=models.BooleanField(default=False, verbose_name='Visible on Home-Page (after entering access code)'),
        ),
    ]
