# Generated by Django 3.0.5 on 2020-10-28 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import labview.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', djongo.models.fields.EmbeddedField(model_container=labview.models.Registration)),
                ('public_key_fingerprint', models.CharField(max_length=50)),
                ('session_key_encrypted', models.CharField(max_length=50)),
                ('aes_instance_iv', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('sample', djongo.models.fields.ArrayField(model_container=labview.models.Sample)),
                ('barcode', models.CharField(max_length=50)),
                ('time', models.DateTimeField(max_length=50)),
                ('name_encrypted', models.CharField(max_length=50)),
                ('address_encrypted', models.CharField(max_length=50)),
                ('contact_encrypted', models.CharField(max_length=50)),
                ('password_hash', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('updated_on', models.DateTimeField()),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
