# Generated by Django 3.0.5 on 2020-10-29 12:55

from django.db import migrations, models
import djongo.models.fields
import labview.models


class Migration(migrations.Migration):

    dependencies = [
        ('labview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('barcode', models.CharField(max_length=50)),
                ('batch', models.CharField(max_length=50)),
                ('rack', models.CharField(max_length=50)),
                ('registrations', djongo.models.fields.ArrayField(model_container=labview.models.Registration)),
            ],
        ),
        migrations.DeleteModel(
            name='KeyInformation',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
