name: build-test-workflow
on:
  push:
    branches:
      - '*'
      - '!master'
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/production' && github.ref != 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: |
          cp example.env .env
          cp example.env .env-docker
          docker-compose up -d
      - name: Test
        run: |
          docker container ls
          docker exec covidtest_app pytest --cov=.
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/production'
    steps:
      - name: Triggering webhook
        uses: wei/curl@v1
        with:
          args: "https://webhooks.covidtest-hd.de/hooks/deployment?token=${{ secrets.WEBHOOK_KEY }}"